export const tags = [
    "Hidden Founder",
    "Strict Hidden",
    "Emerging Founder",
    "Stealth/Early Founder",
    "Discovery Candidate",
    "Stealth Candidate",
    "AI/Tech Candidate",
    "AI Founder",
    "Tech Founder",
    "Current Founder",
    "Previous Founder",
    "AI Startup",
    "Accelerator Participant",
    "Building in Stealth",
    "Currently Unemployed",
    "Female Founder",
    "Scaleup Alumni",
    "Worked in Big Tech",
    "Migrant",
]