export const tags = [
    "Hidden Founder",
    "AI Founder",
    "Tech Founder",
    "Current Founder",
    "Previous Founder",
    "AI Startup",
    "Accelerator Participant",
    "Building in Stealth",
    "Currently Unemployed",
    "Female Founder",
    "Scaleup Alumni",
    "Worked in Big Tech",
    "Migrant",
]